### ISSUE TITLE
Build a serverless social media image service

### ISSUE THREAD

**Issue by Bobface** [Ideamarket/gitcoin-bounties#23]
[ideamarket.io](https://ideamarket.io) | [Twitter](https://twitter.com/ideamarkets_) | [Discord](https://discord.gg/zh6JcGv)

[ideamarket.io](https://ideamarket.io) is displaying the social media images of various accounts from different platforms. For that purpose we are currently utilizing a custom fork of [unavatar](https://github.com/Kikobeats/unavatar) (see our fork [here](https://github.com/Ideamarket/unavatar)). Unfortunately with growing traffic, self-hosting this application is hitting its limits.

This task is to develop a serverless application which will replace unavatar. It should be a serverless application running on *AWS Lambda* which offers an API which can be called via HTTPS and returns the URL to a requested image. For example, requesting `GET /twitter/elonmusk` returns the URL to Elon's Twitter user image.

Since user images do not change often, a caching mechanism should be built in by using *AWS S3*. When the API is invoked, the application checks if it has a version of the image available in the S3 bucket which is not too old. If so, it simply returns the URL to the image in the S3 bucket. If not, it downloads an updated version of the image, replaces the outdated image in the S3 bucket, and then responds with the URL to the image in the S3 bucket.

To save as much traffic and loading time as possible, the images should be scaled down before being placed in the S3 bucket.

Lastly, the application should use environment variables to enable us to prvoide a simple configuration (proxy credentials, image scaling size, etc.).

Other technical requirements:
- The application should utilize the [Serverless SDK](https://www.serverless.com/)
- Uses Typescript
- The application's code is structured in a way which easily allows to add more platforms at a later point, similar to unavatar's current implementation
- Both Twitter and Substack are supported initially (see existing scraping code [for Twitter](https://github.com/Ideamarket/unavatar/blob/master/src/providers/twitter.js) and [for Substack](https://github.com/Ideamarket/unavatar/blob/master/src/providers/substack.js))

If this bounty sounds interesting to you, please reach out to Alexander on Discord before applying to discuss further details: Alexander Schlindwein#9040

**Prize**

- $1000 USDC

**Ideamarket Resources**
- [Ideamarket website](https://ideamarket.io)
- [Ideamarket Discord](https://discord.gg/zh6JcGv)

**PS — We’re hiring**

- VP of Development — $125k
- Backend Developer — $110k

**Comment by acolytec3** [comment]
Done 😁
