### ISSUE TITLE
ERC721 Contract 

### ISSUE THREAD

**Issue by ssemess** [Ideamarket/gitcoin-bounties#24]
Hey bounty hunters!

I have 2 tasks. Need a ERC721 Contract basically openzeppelin's  “opensea-creatures” on github. + website web3 connection with metamask. I'm offering a generous fee and a reasonable amount of time for my bounty.

**My tasks:**

1) I need a ERC721 smart contract basically like “opensea creatures” on github. I want to minted my NTFs on from my website for "my website is ready" who want to get it. the ERC721 smart contract must have bonding curve formula. for an example i have 1K NFT and my NFTs price will be different like 0-100 = 0.001 eth 200-300 = 0.002 .... to 1000 = 0.1 = eth like so on.

2) thanks to the ERC721 smart contract, people can minted my nfts on my website. this part is web3 integration with metamask.

**The ERC721 smart contract must have:**

- bonding curve formula
- by nature of ERC721 "minting function"
- the contract must be simple and not upgradeable
- it must be safe I don't want to see back doors inside
- it must be tested in test networks before the getting bounty award
- of course i use my eth wallet on the contract and I should only have control do you have a any advice? should it send payments automatically on a scheduled date?

**PS:**

I know how ERC721 smart contracts works. I've been researching for about 2 weeks and I've tried github clone myself with youtube videos. Theoretically, I have a good command of the business model. it needs ifps, infura, alchemyapi, truffle and ganache so on. So far, 15 developers have offered me on deadline and budget. 

**FYI:**

- A demo must be included. I should see that your ERC721 runs smoothly on the test net and web3 website edition according to my 2 tasks.

**Submissions will be judged by:**

All submissions must be MIT licensed, otherwise we cannot accept them. I must have all of rights ERC721 smart contract like as being digital and physical.

- Code quality, complexity, and creativity, UX simplicity

**Bounty Award:**

$750  = as Ethereum to the winner

**Winner Announcement Date:**

We will choose the winning submission by April 3 2021.

**Comment by Bobface** [comment]
@ssemess This repository is only for official Ideamarket bounties, please don't post your own bounties here. Thanks!

**Comment by ssemess** [comment]
sorry that's my fault. thanks!
